Models/ErrorViewModel.cs
namespace Lab3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ProgrammingLanguageModel.cs
namespace Lab3.Models;

public record ProgrammingLanguage(Guid Id, string NamePL, string reithingPL);
public record ProgrammingLanguageListDescription(Guid Id, string Name);

public record ProgrammingLanguageList : ProgrammingLanguageListDescription
{
    private IList<ProgrammingLanguage>? pl;

    public IList<ProgrammingLanguage> PL { get; init; }

    public ProgrammingLanguageList(Guid id, string name, IList<ProgrammingLanguage> pl) : base(id, name)
    {
        PL = pl;
    }
    
}

Controllers/ProgrammingLanguageController.cs
using Lab3.Data;
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab3.Controllers
{
    public class ProgrammingLanguageController : Controller
    {
        private readonly ILogger<ProgrammingLanguageController> _logger;
        private readonly IProgrammingLanguageListRepository _programminglanguageListRepository;

        public ProgrammingLanguageController(IProgrammingLanguageListRepository programminglanguageListRepository, ILogger<ProgrammingLanguageController> logger)
        {
            _programminglanguageListRepository = programminglanguageListRepository ?? throw new ArgumentNullException(nameof(programminglanguageListRepository));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public IActionResult Index(Guid id)
        {
            var programminglanguagelists = _programminglanguageListRepository.GetLists();
            if (!programminglanguagelists.Any())
                return RedirectToAction(nameof(ProgrammingLanguageManagerController.Index), "ProgrammingLanguageManager");

            var selectedListId = programminglanguagelists.SingleOrDefault(x => x.Id == id)?.Id ?? programminglanguagelists.First().Id;
            var selectedList = _programminglanguageListRepository.GetListById(selectedListId);

            var viewModel = new IndexViewModel(
                programminglanguagelists,
                selectedListId,
                selectedList.PL);
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult AddProgrammingLanguage(/*[FromBody]*/ AddProgrammingLanguageViewModel addModel)
        {
            try
            {
                var programminglanguageList = _programminglanguageListRepository.GetListById(addModel.ProgrammingLanguageListId) ?? throw new ArgumentNullException(nameof(addModel));
                programminglanguageList.PL.Add(new ProgrammingLanguage(Guid.Empty, addModel.Name, addModel.reitinght));
                _programminglanguageListRepository.SaveProgrammingLanguageList(programminglanguageList);
            }
            catch (ArgumentException ex)
            {
                _logger.LogError("Список не найден.");
            }
            return RedirectToAction(nameof(Index), new { id = addModel.ProgrammingLanguageListId });
        }

        public record IndexViewModel(
    IList<ProgrammingLanguageListDescription> ProgrammingLanguagetList,
    Guid SelectedProgrammingLanguageListId,
    IList<ProgrammingLanguage> ProgrammingLanguages);

        public record AddProgrammingLanguageViewModel(
             Guid ProgrammingLanguageListId,
             string Name,
             string reitinght);
    }
}

Controllers/ProgrammingLanguageManagerController.cs
using Microsoft.AspNetCore.Mvc;
using Lab3.Data;
using Lab3.Models;

namespace Lab3.Controllers
{
    public class ProgrammingLanguageManagerController : Controller
    {
        private readonly IProgrammingLanguageListRepository _ProgrammingLanguageListRepository;

        public ProgrammingLanguageManagerController(IProgrammingLanguageListRepository ProgrammingLanguageListRepository)
        {
            _ProgrammingLanguageListRepository = ProgrammingLanguageListRepository;
        }

        public IActionResult Index()
        {
            var ProgrammingLanguagelists = _ProgrammingLanguageListRepository.GetLists();

            return View(ProgrammingLanguagelists);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();  
        }

        [HttpPost]
        public IActionResult Create(ProgrammingLanguageListDescription ProgrammingLanguageListDescription)
        {
            _ProgrammingLanguageListRepository.SaveProgrammingLanguageList(new ProgrammingLanguageList(Guid.Empty, ProgrammingLanguageListDescription.Name, new List<ProgrammingLanguage>()));
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(Guid id)
        {
            _ProgrammingLanguageListRepository.DeleteProgrammingLanguageList(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/ProgrammingLanguage/Index.cshtml
@model Lab3.Controllers.ProgrammingLanguageController.IndexViewModel?
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Список типов языков программирования</h1>
</div>

<form class="row mb-3">
    <div class="col-10">
        <select id="PLSelect" class="col-sm-9 form form-select">
            @foreach (var item in Model.ProgrammingLanguagetList)
            {
                if (Model.SelectedProgrammingLanguageListId == item.Id)
               { <option value="@item.Id" selected>@item.Name</option>}
                else
                {<option value="@item.Id">@item.Name</option>}
            }
        </select>
    </div>
    <div class="col-2">
        <a asp-action="Index" asp-controller="ProgrammingLanguageListManager">начальное окно</a>
    </div>
</form>


<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Наименование ЯП</th>
                <th>Рейтинг</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ProgrammingLanguages)
            {
                <tr>
                    <td>@item.NamePL</td>
                    <td>@item.reithingPL</td>
                </tr>
            }

        </tbody>

    </table>
</div>

<form asp-action="AddProgrammingLanguage" class="row">

    <input name="ProgrammingLanguageListId" id="ProgrammingLanguageListId" type="hidden" value="@Model.SelectedProgrammingLanguageListId" />
    <div class="col-6">
        <input class="form-control" name="Name" type="text" placeholder="Наименование ЯП" />
    </div>

    <div class="col-4">
        <input class="form-control" name="Reiting" type="text" placeholder="Рейтинг ЯП" />
    </div>


    <div class="col-2">
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </div>
</form>

@section Scripts{
    <script>
            $(function(){
            $("#PLSelect").change( function(){
                window.location.href = "/StudeProgrammingLanguagent/Index/" + this.value;
            });
        });
    </script>
}

Views/ProgrammingLanguageManager/Create.cshtml
@model Lab3.Models.ProgrammingLanguageListDescription

@{
    ViewData["Title"] = "Create";
}

<h1>Новая группа ЯП</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Name" class="control-label">Введите название типа языка программирования</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать группу ЯП" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/ProgrammingLanguageManager/Index.cshtml
@model IEnumerable<Lab3.Models.ProgrammingLanguageListDescription>

@{
    ViewData["Title"] = "Index";
}

<h1>Список типов ЯП</h1>

<p>
    <a asp-action="Create">Создать новую группу ЯП</a>
</p>
<table class="table">
    <thead>
        <tr>
           <th>
               Название ЯП
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  }) |
                @Html.ActionLink("Удалить", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    <a asp-action="Index" asp-controller="ProgrammingLanguage">Просмотреть группы ЯП</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Lab3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>